var CATALOG = {
  LOAD   : {param:true , code: 1},
  STORE  : {param:true , code: 2},
  ADD    : {param:true , code: 3},
  SUB    : {param:true , code: 4},
  MUL    : {param:true , code: 5},
  DIV    : {param:true , code: 6},
  MOD    : {param:true , code: 7},
  CMP    : {param:true , code: 8},
  LSHIFT : {param:true , code: 9},
  RSHIFT : {param:true , code:10},
  AND    : {param:true , code:11},
  OR     : {param:true , code:12},
  NOT    : {param:false, code:13},
  XOR    : {param:true , code:14},
  JUMP   : {param:true , code:15},
  JUMPGT : {param:true , code:16},
  JUMPEQ : {param:true , code:17},
  JUMPLT : {param:true , code:18},
  SET    : {param:true , code:19},
  END    : {param:false, code:31}
};