application: hunterlarcopersonal
version: webenv
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /system
  static_dir: system

- url: .*
  script: app.app

libraries:
- name: webapp2
  version: "2.5.1"